name: Main

on: [push]

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bootstrap

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: pip

      - name: Verify Python requirements
        run: |
          awk '/^pip==/{p=1;print;next}/^[^ ]/{p=0}p' requirements.txt > /tmp/requirements.txt
          pip install --no-deps -r /tmp/requirements.txt
          awk '/^(pip-tools|click|pep517|tomli|wheel)==/{p=1;print;next}/^[^ ]/{p=0}p' requirements.txt > /tmp/requirements.txt
          pip install --no-deps -r /tmp/requirements.txt
          echo "-c $(pwd)/requirements.txt" > /tmp/requirements.in
          pip-compile --quiet --allow-unsafe --generate-hashes --build-isolation --output-file /tmp/requirements.txt requirements.in /tmp/requirements.in
          grep -v '^\s*#' requirements.txt | diff - <(grep -v '^\s*#' /tmp/requirements.txt)


      - name: Install Python requirements
        run: |
          pip install --no-deps -r /tmp/requirements.txt
